name: Daily sync

on:
    schedule:
        - cron: "0 13 * * *"
    workflow_dispatch:

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - run: docker pull ghcr.io/${{ github.repository }}:latest
            - run: docker run
                  --env GEMINI_API_KEY
                  --env GOOGLE_STORE_RESOURCE_NAME
                  ghcr.io/${{ github.repository }}:latest
              env:
                  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
                  GOOGLE_STORE_RESOURCE_NAME: ${{ secrets.GOOGLE_STORE_RESOURCE_NAME }}
